 platform :ios, '9.0'

target 'sad' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for sad
  pod 'SDWebImage'
  pod 'MBProgressHUD'
  pod "AFNetworking"
  pod 'MJRefresh'
  pod 'MJExtension'
  pod 'Masonry'
  pod 'SDCycleScrollView'
end
