 platform :ios, '9.0'

target 'gitTest' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!


  # Pods for gitTest
	  pod 'SDWebImage'
  pod 'MBProgressHUD'
  pod "AFNetworking"
  pod 'MJRefresh'
  pod 'MJExtension'
  pod 'Masonry'
end
